apiVersion: v1
kind: Secret
metadata:
  name: cloudcart-secrets
  namespace: cloudcart
type: Opaque
# IMPORTANT: values must be base64 encoded
# Run: echo -n "your-value" | base64
data:
  DB_USER: YWRtaW4=
  DB_PASSWORD: YWRtaW4xMjMh
  MYSQL_ROOT_PASSWORD: cm9vdDEyMyE=
  JWT_SECRET: Y2xvdWRjYXJ0X2p3dF9zZWNyZXRfMjAyNl9wcm9kdWN0aW9uIQ==